### ISSUE TITLE
Can't install on Manjaro Linux - No such file or directory

### ISSUE THREAD

**Issue by vlandemart** [ahrbe1/plasticscm-appimage#1]
![image](https://user-images.githubusercontent.com/19672958/200176642-9be8ceb5-5127-48da-9843-e7dc75ded8f7.png)

Installation script is getting error at step 15

**Comment by ahrbe1** [comment]
Hrm looks like the AppImage failed to build for some reason prior to step 15. I'll do a build and see if I can replicate it.

**Comment by ahrbe1** [comment]
So it looks like this may be an issue with fuse, which is required by pkg2appimage. I can replicate the issue, trying to find a fix for it.

**Comment by ahrbe1** [comment]
Ok, I think I've resolve this.

You'll need to make sure you have fuse v2 installed on the host system in addition to docker. 

Fuse is required under-the-hood by pkg2appimage, but we didn't explicitly check for that before. It looks like docker/apparmor became more strict on newer distros, which prevented pkg2appimage from being able to use fuse inside the docker container. 

I've updated the readme file and also added some code-checks to check for docker and fuse. Also, I made the script more strict, and it should now fail properly if a command it calls fails. 

Try out the bugfix-01 branch and see if that works for you.

LMK if you bump into other issues with that patch. I tested this on Ubuntu 22.04, but I can install Manjaro in a VM to troubleshoot additional distro-specific issues if necessary.

**Comment by vlandemart** [comment]
With fuse v2 installed I was able to go past all 20 steps in installation, but no files were generated to /out, and no log file is present in directory
So still no luck with installing it

**Comment by ahrbe1** [comment]
Ok. Thanks for the update. If you have a chance to post what's written to stdout, I'd appreciate it. What version of Manjaro are you on? I'll do a clean install in a VM tonight and see how far I get.

**Comment by vlandemart** [comment]
Here is full stdout - [log.txt](https://github.com/ahrbe1/plasticscm-appimage/files/9962352/log.txt)
My Manjaro version is 22.0, KDE edition

**Comment by ahrbe1** [comment]
Ok. Status update. I got Manjaro KDE edition installed in a VM, and fixed the issues that prevented installation. It looks like the PlasticSCM guys renamed some files which broke some of the commands used to build the AppImage. So that part works now. However, when I run it, I'm getting an error about "failed to initialize GTK" on Manjaro. So I'm looking into that next.

**Comment by ahrbe1** [comment]
So I pushed some more commits to that bugfix-01 branch. The script now clearly reports success or failure status. I also added some scripts for analyzing the resulting AppImage. The AppImage should build correctly now on Manjaro. The GUI boots up, and I can log in, but then the app reports that GTK error. I tested this on Ubuntu 22.04 also, and I'm seeing the same GTK issue there. So tomorrow I'll go back and test on 20.04 and 18.04 and see if it still occurs there. It used to work on those platforms, anyways. The log files under `~/.plastic4/logs` report some kind of threading error in Gtk/Glib, which makes me think the official Linux build might actually be broken at the moment. I'll let you know what I find.

**Comment by ahrbe1** [comment]
Ok. Getting closer. Turns out the PlasticSCM folks have done a pretty major overhaul. They renamed some packages, removed some commands, and removed their mono and gtk dependencies. This script should now be more robust to such changes. It appears to work now for me on Ubuntu 22.04 and Manjaro.

**Comment by ahrbe1** [comment]
Pushed up all the changes I have to the bugfix-01 branch. LMK if you still have issues with it.

**Comment by EnricoMonese** [comment]
I tried this on Arch. I think it builds fine, but it had trouble linking the files. I ran it again with `--build` and linked manually to make it work.

Running with `--uninstall` used the wrong path however `rm -f /root/.local/bin/plasticgui`. Maybe it's because I ran the script with `sudo`? (If that's the problem then adding my user to the `docker` group, like the readme says, should fix this)
